"""chat schema upgrade

Revision ID: 67f2d905230a
Revises: d59e1c27ddf0
Create Date: 2026-07-17 23:39:45.000559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67f2d905230a'
down_revision: Union[str, Sequence[str], None] = 'd59e1c27ddf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#enums 

content_type_enum = postgresql.ENUM(
    'TEXT', 'MARKDOWN', 'JSON',
    name='content_type_enum'
)

message_status_enum = postgresql.ENUM(
    'PENDING', 'STREAMING', 'COMPLETED', 'FAILED',
    name='message_status_enum'
)

message_role_enum = postgresql.ENUM(
    'USER', 'ASSISTANT', 'SYSTEM', 'TOOL',
    name='message_role_enum'
)

title_status_enum = postgresql.ENUM(
    'PENDING', 'GENERATED', 'CUSTOM',
    name='title_status_enum'
)

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # ✅ CREATE ENUM TYPES FIRST
    content_type_enum.create(bind, checkfirst=True)
    message_status_enum.create(bind, checkfirst=True)
    message_role_enum.create(bind, checkfirst=True)
    title_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summary',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('last_summarized_sequence', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user_chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('chat_id', name='uq_summary_chat')
    )
    op.create_index(op.f('ix_conversation_summary_summary_id'), 'conversation_summary', ['summary_id'], unique=True)
    op.add_column('chat_messages', sa.Column('sequence_number', sa.BigInteger(), nullable=False,server_default='0'))
    op.add_column('chat_messages', sa.Column('parent_message_id', sa.UUID(), nullable=True))
    op.add_column('chat_messages', sa.Column('content_type', content_type_enum , nullable=False, server_default=sa.text("'TEXT'")))
    op.add_column('chat_messages', sa.Column('status', message_status_enum, nullable=False, server_default=sa.text("'PENDING'")))
    
    op.add_column('chat_messages', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_messages', sa.Column('updated_at', sa.DateTime(), nullable=False,server_default=sa.func.now()))
    op.execute("""
        ALTER TABLE chat_messages
        ALTER COLUMN role TYPE message_role_enum
        USING role::message_role_enum
    """)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_message_chat', 'chat_messages', ['chat_id'], unique=False)
    op.create_index('idx_message_role', 'chat_messages', ['chat_id', 'role'], unique=False)
    op.create_index('idx_message_sequence', 'chat_messages', ['chat_id', 'sequence_number'], unique=False)
    op.create_index('idx_metadata', 'chat_messages', ['metadata'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('uq_chat_sequence', 'chat_messages', ['chat_id', 'sequence_number'])
    op.create_foreign_key(
    'fk_chat_messages_parent',
    'chat_messages',
    'chat_messages',
    ['parent_message_id'],
    ['message_id'],
    ondelete='SET NULL'
)
    op.add_column('user_chats',  sa.Column('title_status', title_status_enum, nullable=False, server_default=sa.text("'PENDING'")))
    op.add_column('user_chats', sa.Column('next_sequence', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('user_chats', sa.Column('last_message_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('user_chats', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_chats', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('user_chats', 'chat_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_chat_archive', 'user_chats', ['user_id', 'is_archived'], unique=False)
    op.create_index('idx_chat_last_message', 'user_chats', ['user_id', 'last_message_at'], unique=False)
    op.create_index('idx_chat_user', 'user_chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_user', table_name='user_chats')
    op.drop_index('idx_chat_last_message', table_name='user_chats')
    op.drop_index('idx_chat_archive', table_name='user_chats')
    op.alter_column('user_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_chats', 'chat_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_chats', 'updated_at')
    op.drop_column('user_chats', 'is_archived')
    op.drop_column('user_chats', 'last_message_at')
    op.drop_column('user_chats', 'next_sequence')
    op.drop_column('user_chats', 'title_status')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint('uq_chat_sequence', 'chat_messages', type_='unique')
    op.drop_constraint('fk_chat_messages_parent', 'chat_messages', type_='foreignkey')
    op.drop_index('idx_metadata', table_name='chat_messages', postgresql_using='gin')
    op.drop_index('idx_message_sequence', table_name='chat_messages')
    op.drop_index('idx_message_role', table_name='chat_messages')
    op.drop_index('idx_message_chat', table_name='chat_messages')
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chat_messages', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='message_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('chat_messages', 'updated_at')
    op.drop_column('chat_messages', 'metadata')
    op.drop_column('chat_messages', 'status')
    op.drop_column('chat_messages', 'content_type')
    op.drop_column('chat_messages', 'parent_message_id')
    op.drop_column('chat_messages', 'sequence_number')
    op.drop_index(op.f('ix_conversation_summary_summary_id'), table_name='conversation_summary')
    op.drop_table('conversation_summary')
    bind = op.get_bind()
    title_status_enum.drop(bind, checkfirst=True)
    message_role_enum.drop(bind, checkfirst=True)
    message_status_enum.drop(bind, checkfirst=True)
    content_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
