"""created processing status model and established relation with document model

Revision ID: c060196772c9
Revises: 78724573adf0
Create Date: 2026-06-04 01:37:53.138293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c060196772c9'
down_revision: Union[str, Sequence[str], None] = '78724573adf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_status',
    sa.Column('processing_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatusenum'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['user_documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('processing_id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_processing_status_processing_id'), 'processing_status', ['processing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_status_processing_id'), table_name='processing_status')
    op.drop_table('processing_status')
    # ### end Alembic commands ###
