import re
from typing import Optional

from langchain_core.messages import HumanMessage, SystemMessage

from app.core.llm_client import llm_client as default_llm_client
from app.services.logger_service import get_logger

logger = get_logger(__name__)

TITLE_SYSTEM_PROMPT = (
    "You are a precise conversation titler. Generate a concise, natural 3 to 6 word title "
    "summarizing a chat session based on the user's initial query and assistant response. "
    "Guidelines:\n"
    "- Output ONLY the title text (3-6 words).\n"
    "- Do NOT use quotation marks, backticks, or trailing punctuation.\n"
    "- Do NOT prefix with 'Title:', 'Subject:', or similar labels.\n"
    "- Capitalize appropriately."
)


class ChatTitleService:
    """
    Pure LLM Summarizer for generating short (3-6 word) titles for new conversation threads.

    Responsibilities:
        - Generating concise titles using a lightweight LLM call after the initial exchange
        - Cleaning LLM title output (stripping quotes, prefixes, and excess punctuation)
        - Providing robust fallback mechanisms if LLM invocation fails or returns invalid output
    """

    def __init__(self, llm_client_instance=None):
        """
        Initializes ChatTitleService.

        Args:
            llm_client_instance (Optional[LLMClient]): LLM client instance (defaults to global llm_client).
        """
        self.logger = logger
        self.llm_client = llm_client_instance or default_llm_client

    async def generate_title(
        self,
        user_query: str,
        assistant_response: str = "",
    ) -> str:
        """
        Asynchronously generates a 3-6 word title for a chat based on initial user query and assistant response.

        Includes fallback logic to derive title directly from user_query if LLM invocation fails.

        Args:
            user_query (str): The initial user question or prompt.
            assistant_response (str): The initial response generated by the assistant (Optional).

        Returns:
            str: Generated or fallback 3-6 word title.
        """
        if not user_query or not user_query.strip():
            self.logger.warning("Empty user query provided for title generation. Returning default title.")
            return "New Chat"

        cleaned_user_query = user_query.strip()
        cleaned_assistant_response = (assistant_response or "").strip()

        try:
            self.logger.info("Invoking LLM for title generation...")
            llm = self.llm_client.get_llm()

            user_content = f"User Query: {cleaned_user_query}"
            if cleaned_assistant_response:
                # Truncate assistant response if extremely long for prompt efficiency
                user_content += f"\nAssistant Response: {cleaned_assistant_response[:1000]}"

            messages = [
                SystemMessage(content=TITLE_SYSTEM_PROMPT),
                HumanMessage(content=user_content),
            ]

            response = await llm.ainvoke(messages)
            raw_title = response.content if hasattr(response, "content") else str(response)

            processed_title = self._clean_and_truncate_title(raw_title)
            if processed_title:
                self.logger.info(f"Successfully generated chat title: '{processed_title}'")
                return processed_title

            self.logger.warning("LLM title output was empty after cleaning. Using fallback title.")
            return self._fallback_title(cleaned_user_query)

        except Exception as e:
            self.logger.warning(f"LLM title generation failed ({str(e)}). Using fallback title.")
            return self._fallback_title(cleaned_user_query)

    def generate_title_sync(
        self,
        user_query: str,
        assistant_response: str = "",
    ) -> str:
        """
        Synchronously generates a 3-6 word title for a chat thread.

        Args:
            user_query (str): The initial user question or prompt.
            assistant_response (str): The initial response generated by the assistant (Optional).

        Returns:
            str: Generated or fallback 3-6 word title.
        """
        if not user_query or not user_query.strip():
            return "New Chat"

        cleaned_user_query = user_query.strip()
        cleaned_assistant_response = (assistant_response or "").strip()

        try:
            self.logger.info("Invoking LLM (sync) for title generation...")
            llm = self.llm_client.get_llm()

            user_content = f"User Query: {cleaned_user_query}"
            if cleaned_assistant_response:
                user_content += f"\nAssistant Response: {cleaned_assistant_response[:1000]}"

            messages = [
                SystemMessage(content=TITLE_SYSTEM_PROMPT),
                HumanMessage(content=user_content),
            ]

            response = llm.invoke(messages)
            raw_title = response.content if hasattr(response, "content") else str(response)

            processed_title = self._clean_and_truncate_title(raw_title)
            if processed_title:
                self.logger.info(f"Successfully generated sync chat title: '{processed_title}'")
                return processed_title

            return self._fallback_title(cleaned_user_query)

        except Exception as e:
            self.logger.warning(f"LLM sync title generation failed ({str(e)}). Using fallback title.")
            return self._fallback_title(cleaned_user_query)

    def _clean_and_truncate_title(self, raw_title: str) -> str:
        """
        Cleans LLM-generated title string by removing quotes, labels, and extra whitespace, enforcing 3-6 word limit.

        Args:
            raw_title (str): Raw string returned by LLM.

        Returns:
            str: Cleaned and formatted title string.
        """
        if not raw_title:
            return ""

        title = raw_title.strip()

        # Remove leading prefix labels like 'Title:', 'Subject:', 'Topic:'
        title = re.sub(r"^(title|subject|topic|name):\s*", "", title, flags=re.IGNORECASE)

        # Remove enclosing quotation marks and markdown formatting
        title = title.strip("\"'`#*")

        # Remove trailing period or trailing punctuation
        title = title.rstrip(".")

        # Split into words and limit to maximum 6 words
        words = title.split()
        if len(words) > 6:
            words = words[:6]

        cleaned_title = " ".join(words).strip()
        return cleaned_title

    def _fallback_title(self, user_query: str) -> str:
        """
        Derives a clean fallback title from the initial user query when LLM generation is unavailable.

        Args:
            user_query (str): The user prompt text.

        Returns:
            str: Truncated 3-6 word title derived from user prompt.
        """
        if not user_query:
            return "New Chat"

        # Remove special control characters and clean up spaces
        clean_text = re.sub(r"[^\w\s-]", "", user_query).strip()

        words = clean_text.split()
        if not words:
            return "New Chat"

        # Take first 3-6 words
        num_words = min(len(words), 6)
        fallback = " ".join(words[:num_words])

        # Capitalize nicely if lowercased
        return fallback.strip().title()
