"""add on delete cascade to refresh_tokens

Revision ID: e8d4c8a40292
Revises: c060196772c9
Create Date: 2026-07-04 01:02:39.227743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d4c8a40292'
down_revision: Union[str, Sequence[str], None] = 'c060196772c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_messages_chat_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'user_chats', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_chats_user_id_fkey'), 'user_chats', type_='foreignkey')
    op.create_foreign_key(None, 'user_chats', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_documents_user_id_fkey'), 'user_documents', type_='foreignkey')
    op.create_foreign_key(None, 'user_documents', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_documents', type_='foreignkey')
    op.create_foreign_key(op.f('user_documents_user_id_fkey'), 'user_documents', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user_chats', type_='foreignkey')
    op.create_foreign_key(op.f('user_chats_user_id_fkey'), 'user_chats', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_chat_id_fkey'), 'chat_messages', 'user_chats', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###
